version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file: ./backend/.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "6415:6415"
    env_file: ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
